// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ISkillModule$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISkillModule";
  readonly sourceName: "contracts/ISkillModule.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"agentAccount","type":"address"},{"internalType":"bytes","name":"input","type":"bytes"}],"name":"execute","outputs":[{"internalType":"bytes","name":"output","type":"bytes"}],"stateMutability":"payable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ISkillModule.sol";
  readonly buildInfoId: "solc-0_8_24-11b576e7240c0a69fa896295a41159eaba2fd2b6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ISkillModule"]: ISkillModule$Type;
    ["contracts/ISkillModule.sol:ISkillModule"]: ISkillModule$Type;
  }
}